---
title: Java进阶-使用 try..catch... 捕获处理异常
date: 2020-02-22 20:13:37
categories:
- Java
comments: false
---

```
try {
	可能出现异常的代码；
}catch(异常类型1 变量) {
	处理异常的代码；
}catch(异常类型2 变量) {
	处理异常的代码；
}...
```

<!-- more -->                                                                                                                                                                                                                                                                                                                                                                                                                                                     

1. `catch` 语句块可以写多个
2. 但是从上到下`catch`，必须从小类型异常到大类型异常进行捕捉
3. 最多执行一个`catch` 语句块，执行结束后`try...catch...` 就结束了

```java
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

public class ExceptionTest04 {

	public static void main(String[] args) {
		try {
			FileInputStream fils = new FileInputStream("a");
			System.out.println("测试"); // 上面的代码出现异常，try 语句块的代码不再继续执行，直接进入 catch 语句块执行
			fils.read();
		} catch (FileNotFoundException e) {
			System.out.println("读取的文件不存在"); // 读取的文件不存在

			// FileNotFoundException 将 Object 中的 toString 方法重写
			System.out.println(e); // java.io.FileNotFoundException: a (系统找不到指定的文件。)
		} catch (IOException e) {
			System.out.println("其他IO异常");
		}
		System.out.println("AB"); // AB
	}
}
```

